local_costmap:
   global_frame: odom 
   robot_base_frame: base_footprint
   update_frequency: 2
   publish_frequency: 2 
   width:  18
   height: 18
   resolution: 0.025
   transform_tolerance: 0.5
   static_map: false
   rolling_window: true
   inflation_radius: 0.06 #The radius in meters to which the map inflates obstacle cost values.0.5